### ISSUE TITLE
Blocks not showing up in WP editor

### ISSUE THREAD

**Issue by StudioRATATA** [Log1x/poet#22]
Hi Brandon,

I'm unable to get the blocks to work in the editor. 
What I noticed is that the CPT `books` from the `/config/poet.php` does show up. These are the steps I took. Not that I did them both on my existing sage 10 project and a clean install of a sage 10 project. Both with the same result.

- `composer require log1x/poet`
- `wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"` returned `Unable to locate publishable resources.` (this happens to all packages I try to install with vendor:publish)
- So I manually copied `/config/poet.php`
- CPT `books` shows up. Letting me think the config works.
- [Added a block like described in the readme](https://github.com/Log1x/poet#registering-a-block) So:
- Added accordion with the attributes
- added the example code to `/resources/views/blocks/accordion.blade.php`

With this I don's see the block in the editor. 
I also changed the namespace and block name to check with more unique names. 

Is there something I'm not doing right?

**Comment by Log1x** [comment]
did you register the block in javascript?

**Comment by aitormendez** [comment]
I have "Unable to locate publishable resources" too.

**Comment by Log1x** [comment]
Do `wp acorn vendor:publish` without specifying the provider and choose from the list

**Comment by StudioRATATA** [comment]
> did you register the block in javascript?

Ah no, I did not. I naively assumed the plugin handled the block registration, much like the acf approach in `Log1x/acf-composer` since I read nothing about it in the readme. I've worked with wp-blocks boilerplates before. They watch and build the .js files and the build files are being served. 

If I place your snippit simply in a `/App/blocks/accordion/block.js` file (along with a editor.js file) and enqeue them I get an Es6 import error. So I guess I miss extra steps and knowledge :) 

How would I handle this? 

----- 
The `wp acorn vendor:publish` did the trick, thanks. I've had this with several composer plugins. I can now use this elsewhere as well. Thanks Brandon.

**Comment by StudioRATATA** [comment]
Literately seconds later I figured I could place this in the assets folder... Like `/resources/assets/scripts/blocks/accordion/block.js` And import them in the `editor.js`. No luck yet, but now, it builds : )

**Comment by haynzz** [comment]
I have to be honest, if it wasn't for this issue thread I would not have been able to get it running.
But, now it worked for me.
I assume it's because I'm new to everything. I have no experience in WP Theme development and I have started with sage10. So, I have also never created my own Gutenberg block before.
The major issues that needed trial and error and closer reading for me were:

1. I have to register via the new block via `editor.js` - got to know the `registerBlockType` this way
2. the namespaces have to match everywhere (`sage/<myblock>` by default) so that the `resources/views/blocks/<myblock>.balde.php` file is loaded – learned that it works as I expect it when I do not provide a `save` property during block registration 
    - Disclaimer not tried to get InnerBlocks working yet
 
One question that is still open for me: Can I set the block-category for a block in the `poet.php` or does it need to be via `registerBlockType` in the JS files?
